### ISSUE TITLE
Configure Continious Integration

### ISSUE THREAD

**Issue by humb1t** [SamaraITCommunity/admin#4]
CI should include:

- dependencies check
- types check
- format/style check

**Comment by humb1t** [comment]
Deps and types check done

**Comment by speker2010** [comment]
You mean [eslint](https://eslint.org/), [typescript eslint](https://github.com/typescript-eslint/typescript-eslint/blob/master/docs/getting-started/linting/README.md)? 
What about [airbnb](https://www.npmjs.com/package/eslint-config-airbnb-typescript) for rules config?

**Comment by humb1t** [comment]
@speker2010 - lints good, I think I already made it - please check.
Rules config should be aligned with the current style. I'm ok with any style. @fax1ty what do you think about airbnb?

**Comment by fax1ty** [comment]
@humb1t https://github.com/airbnb/javascript/tree/master/packages/eslint-config-airbnb 
Тут есть лишние правила для React. Я не совсем понимаю в чём была изначальная идея. Проверять правильность кода (возможность компиляции) или просто добавить правила стилизации?

**Comment by humb1t** [comment]
@fax1ty и то и другое. 
Несмотря на то, что в основном контрибьютишь только ты, стили нужны. airbnb возможно не лучший вариант.
