### ISSUE TITLE
Remove `yarn.lock` from repository

### ISSUE THREAD

**Issue by humb1t** [SamaraITCommunity/admin#9]
Remove `yarn.lock` and add it to `.gitignore`.

**Comment by fax1ty** [comment]
@humb1t https://stackoverflow.com/questions/39990017/should-i-commit-the-yarn-lock-file-and-what-is-it-for

**Comment by humb1t** [comment]
@fax1ty боюсь что пока CI использует npm, а разработчики `yarn install` без `--frozen-lockfile` смысла держать его тут и постоянно пушить нету. Тем более от него могут быть нежелательные конфликты.
